services:
  - type: web
    name: ems-shaikot-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build && npm run seed
    startCommand: node dist/main
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ems-shaikot-frontend.onrender.com

  - type: web
    name: ems-shaikot-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://ems-shaikot-backend.onrender.com
      - key: NODE_ENV
        value: production
